// <auto-generated>
//     This code was generated by a tool: the currency table of the .NET sample,
//     as a resource generator or a source generator would write it.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <copyright file="Currencies.generated.cs" company="Fucini Consulting">
// Copyright (c) 2026 Fucini Consulting. Released under the MIT License; see the
// LICENSE file in the repository root.
// </copyright>

namespace Pricing;

/// <summary>
/// The currencies a quote may be given in, as a generator writes them: a table
/// nobody tests, because nobody wrote it. Coverlet reports every one of its
/// lines as never run, and out of the box Coverage Studio leaves the file out
/// of every total — <c>fuciniCoverage.ignore.generated</c> — so a generated
/// file does not cost the solution its gate. Turn the setting off to see what
/// it would cost.
/// </summary>
public static class Currencies
{
    /// <summary>The ISO 4217 codes the shop prices in.</summary>
    public static readonly string[] Codes = { "EUR", "USD", "GBP", "CHF", "PLN", "CZK", "SEK", "NOK", "DKK", "HUF" };

    /// <summary>The symbol printed before an amount in the given currency.</summary>
    /// <param name="code">An ISO 4217 code.</param>
    /// <returns>The symbol, or the code itself when it has none.</returns>
    public static string Symbol(string code)
    {
        switch (code)
        {
            case "EUR":
                return "€";
            case "USD":
                return "$";
            case "GBP":
                return "£";
            case "CHF":
                return "CHF";
            case "PLN":
                return "zł";
            case "CZK":
                return "Kč";
            case "SEK":
            case "NOK":
            case "DKK":
                return "kr";
            case "HUF":
                return "Ft";
            default:
                return code;
        }
    }

    /// <summary>How many decimals an amount in the given currency is written with.</summary>
    /// <param name="code">An ISO 4217 code.</param>
    /// <returns>Two, or none for a currency that has no minor unit in use.</returns>
    public static int Decimals(string code)
    {
        if (code == "HUF")
        {
            return 0;
        }

        return 2;
    }

    /// <summary>Whether the shop prices in the given currency.</summary>
    /// <param name="code">An ISO 4217 code.</param>
    /// <returns>True when it is in <see cref="Codes"/>.</returns>
    public static bool IsKnown(string code)
    {
        foreach (var known in Codes)
        {
            if (known == code)
            {
                return true;
            }
        }

        return false;
    }
}
